### ISSUE TITLE
Bug with ">" symbol

### ISSUE THREAD

**Issue by rsanchez-macias** [AY1920S2-CS2113-T14-3/tp#11]
When trying to read user input, the ">" symbol display after the user has entered something, when it should be the other way.

**Comment by Bencotti** [comment]
I believe it should be caused by Gradle or Junit - the original skeleton used to work but when I reverted to check it still displayed the same error. The problem is "quick-fixed" by using a println instead. Initially I thought it was because scanner was blocking, but tested false. Other methods such as buffer reader also does not work. 

Hence the solution now is to have the user input on a new line instead.
